# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b6c6fbf40286d1631d5c4ed262b1449f47ea23a930f333417443f850ae61bf2e2973d45d7e9a56c1927726aa9cb16557f4282be947498aacc1bd9525b83728

test:
  secret_key_base: 328ece4d672296519b4c7b533a98c1ccf4ff0b8cd97ab99eabd8222eb75022ce9ada46ce2c543b792aabd69d24b54bfa84db1ef800c53eef0562c1b8a54044f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
